db:
  image: mysql:latest
  environment:
    - MYSQL_DATABASE=maximus
    - MYSQL_USER=root
    - MYSQL_PASSWORD=
    - MYSQL_RANDOM_ROOT_PASSWORD=yes

streama:
  build: .
  links:
    - db:db
  ports:
    - 8080:8080
